#FROM openjdk:17-jdk-slim
#MAINTAINER kevinjia
#COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar
#ENTRYPOINT ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]
#
## notes: some command
## docker build . -t kevinjia1984/accounts:s4
## docker inspect image fffaa25e9bf4
## docker stop/start c44cc84657bcf0bb6745e1466ad8760d6c72c45d9310b3de40df49458e9a4d25