spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  # notes: this will tell gateway server to connect with eureka server to fetch the service info
  cloud:
    gateway:
      discovery:
        locator:
          # notes: set this false will close the default route instead only the custom routes will be used, see application.java
          enabled: false
          # notes: make the app name to be lowercase
          lower-case-service-id: true
      # todo: notes: global timeouts: https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/http-timeouts-configuration.html
      # todo: notes: if the service has circuitbreaker pattern the fallback function will take effect
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Easy Bank Gateway Server Application"
    version: "1.0.0"
# notes: enable the bugging at debug level
logging:
  level:
    com:
      kevinlearn:
        gatewayserver: DEBUG
resilience4j:
  circuitbreaker:
    configs:
      default:
        # notes: monitor 10 requests
        sliding-window-size: 10
        # notes: allow 2 requests when in half-open status (used to decide whether go close or open)
        permitted-number-of-calls-in-half-open-state: 2
        # notes: rate to move from close to open
        failure-rate-threshold: 50
        # notes: wait 10s before move to half open
        wait-duration-in-open-state: 10000
