server:
  port: 8080
# notes: by giving the ms a name will contact configservice for the related profiles
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
# note: mysql db connection (no need to specify driver)
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  #  note: try to run the schema.sql
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
#    note: connect with the configserver
  # note: if set to optional then configserver not running won't fail this accounts ms
  config:
    import: "optional:configserver:http://localhost:8071/"
  # notes: enable the circuitbreaker
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # notes: allow accounts server shut down gracefully
  # send post to : http://localhost:8080/actuator/shutdown
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  # note: for showing info on the eureka server
  info:
    env:
      enabled: true

#endpoints:
#  shutdown:
#    enabled: true

# note: by default a client will send heartbeat signal to the server every 30s
eureka:
  instance:
    # note: register with server with ip  address
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
# note: show on the eureka server when click the client ms url
# info will also show when: http://localhost:8080/actuator/info
info:
  app:
    name: "accounts"
    description: "Easy Bank Accounts Application"
    version: "1.0.0"
# notes: enable the bugging at debug level (the default debugging level in springboot is info)
logging:
  level:
    com:
      kevinlearn:
        accounts: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        # notes: monitor 10 requests
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        # notes: rate to move from close to open
        failure-rate-threshold: 50
        # notes: wait 10s before move to half open
        wait-duration-in-open-state: 10000