server:
  port: 8080
# notes: by giving the ms a name will contact configservice for the related profiles
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
#  todo: note: mysql db connection (no need to specify driver)
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  #  todo: note: try to run the schema.sql
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
#    note: connect with the configserver
  # note: if set to optional then configserver not running won't fail this accounts ms
  config:
    import: "optional:configserver:http://localhost:8071/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # todo: notes: allow accounts server shut down gracefully
  # send post to : http://localhost:8080/actuator/shutdown
  endpoint:
    shutdown:
      enabled: true
  # todo: note: for showing info on the eureka server
  info:
    env:
      enabled: true

#endpoints:
#  shutdown:
#    enabled: true

# todo: note: by default a client will send heartbeat signal to the server every 30s
eureka:
  instance:
    # todo: note: register with server with ip  address
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
# todo: note: show on the eureka server when click the client ms url
# info will also show when: http://localhost:8080/actuator/info
info:
  app:
    name: "accounts"
    description: "Easy Bank Accounts Application"
    version: "1.0.0"
# todo: notes: enable the bugging at debug level
logging:
  level:
    com:
      kevinlearn:
        accounts: DEBUG